export const INTENT_MAP = [
  { intent: 'what_is_tacoin', patterns: ['what is ta coin', 'what is tacoin', 'what is t.a coin', 'about ta coin', 'tell me about', 'explain ta coin'], faqMatch: 'What is T.A Coin?', keywords: ['tacoin', 'company', 'about'] },
  { intent: 'create_account', patterns: ['create account', 'sign up', 'register', 'new account', 'open account', 'join', 'get started'], faqMatch: 'How do I create a T.A Coin account?', keywords: ['create', 'account', 'signup', 'register', 'join'] },
  { intent: 'kyc_documents', patterns: ['kyc document', 'kyc verification', 'what documents', 'verify identity', 'id card', 'passport'], faqMatch: 'What documents do I need for KYC verification?', keywords: ['kyc', 'document', 'verify', 'identity', 'passport'] },
  { intent: 'kyc_time', patterns: ['kyc how long', 'verification time', 'how long kyc', 'kyc pending', 'kyc approval', 'waiting for verification'], faqMatch: 'How long does KYC verification take?', keywords: ['kyc', 'long', 'time', 'pending', 'approval', 'waiting'] },
  { intent: 'mobile_app', patterns: ['mobile app', 'download app', 'ios app', 'android app', 'app store', 'google play', 'download ta coin', 'install app', 'ios version', 'iphone app', 'apple app', 'web app'], faqMatch: 'Is T.A Coin available on mobile?', keywords: ['mobile', 'app', 'download', 'ios', 'android', 'install', 'iphone', 'web'] },
  { intent: 'reset_password', patterns: ['reset password', 'forgot password', 'change password', 'cant login', 'lost password', 'password reset', 'recover password'], faqMatch: 'How do I reset my password?', keywords: ['password', 'reset', 'forgot', 'login', 'recover'] },
  { intent: 'update_account', patterns: ['update account', 'change account', 'edit profile', 'update information', 'change email', 'change phone', 'modify account'], faqMatch: 'How do I update my account information?', keywords: ['update', 'change', 'edit', 'profile', 'information'] },
  { intent: 'cant_access', patterns: ['cant access', 'locked out', 'account locked', 'blocked account', 'unable to login', 'login issue', 'access denied'], faqMatch: 'I can\'t access my account. What should I do?', keywords: ['access', 'locked', 'blocked', 'login', 'problem'] },
  { intent: 'biometric', patterns: ['biometric', 'fingerprint', 'face recognition', 'face id', 'touch id', 'biometric login'], faqMatch: 'How do I enable biometric login?', keywords: ['biometric', 'fingerprint', 'face', 'touch'] },
  { intent: 'delete_account', patterns: ['delete account', 'close account', 'remove account', 'deactivate', 'cancel account', 'terminate account'], faqMatch: 'How do I delete my T.A Coin account?', keywords: ['delete', 'close', 'remove', 'deactivate', 'cancel', 'terminate'] },
  { intent: 'make_payment', patterns: ['make payment', 'pay', 'scan qr', 'qr code', 'send money', 'transfer money', 'how to pay', 'scan to pay'], faqMatch: 'How do I make a payment using T.A Coin?', keywords: ['payment', 'pay', 'qr', 'scan', 'send', 'transfer'] },
  { intent: 'check_balance', patterns: ['check balance', 'wallet balance', 'how much money', 'my balance', 'view balance', 'available balance'], faqMatch: 'How do I check my wallet balance?', keywords: ['balance', 'wallet', 'funds'] },
  { intent: 'deposit', patterns: ['deposit', 'add funds', 'top up', 'fund wallet', 'add money', 'bank transfer', 'load wallet'], faqMatch: 'How do I deposit funds into my T.A Coin wallet?', keywords: ['deposit', 'fund', 'top', 'add', 'bank', 'transfer'] },
  { intent: 'transaction_history', patterns: ['transaction history', 'past transactions', 'payment history', 'view transactions', 'transaction records'], faqMatch: 'How do I check my transaction history?', keywords: ['transaction', 'history', 'records', 'past'] },
  { intent: 'transaction_failed', patterns: ['transaction failed', 'payment failed', 'pending transaction', 'stuck transaction', 'transaction error', 'payment not received', 'failed payment'], faqMatch: 'What should I do if a transaction fails or is pending?', keywords: ['failed', 'pending', 'stuck', 'error', 'transaction'] },
  { intent: 'loans', patterns: ['loan', 'credit', 'borrow', 'lending', 'finance', 'get a loan', 'borrow money'], faqMatch: 'Does T.A Coin provide loans or credit?', keywords: ['loan', 'credit', 'borrow', 'lending', 'finance'] },
  { intent: 'account_security', patterns: ['account secure', 'security', 'how safe', 'is it safe', 'protect account', 'security features', 'how secure'], faqMatch: 'How does T.A Coin keep my account secure?', keywords: ['secure', 'security', 'safe', 'protect', 'encryption'] },
  { intent: 'unauthorized_access', patterns: ['unauthorized', 'hacked', 'someone accessed', 'suspicious activity', 'account compromised', 'stolen account'], faqMatch: 'What should I do if I suspect unauthorized access to my account?', keywords: ['unauthorized', 'hacked', 'suspicious', 'compromised', 'stolen', 'fraud'] },
  { intent: 'data_privacy', patterns: ['personal data', 'data safe', 'privacy', 'data protection', 'my data', 'information safe'], faqMatch: 'Is my personal data safe with T.A Coin?', keywords: ['data', 'privacy', 'personal', 'protection'] },
  { intent: 'report_scam', patterns: ['report scam', 'report phishing', 'report fraud', 'scam', 'phishing', 'fake website', 'suspicious link', 'report', 'fake email', 'how to report', 'report a problem', 'report issue', 'file report', 'make report', 'submit report'], faqMatch: 'How do I report a scam or phishing attempt?', keywords: ['report', 'scam', 'phishing', 'fraud', 'fake', 'suspicious'] },
  { intent: 'contact_support', patterns: ['contact support', 'customer support', 'support email', 'support phone', 'call support', 'reach support', 'talk to someone', 'contact us', 'get help', 'phone number', 'telegram'], faqMatch: 'How do I contact T.A Coin customer support?', keywords: ['contact', 'support', 'phone', 'email', 'telegram', 'call'] },
  { intent: 'support_hours', patterns: ['support hours', 'business hours', 'when available', 'operating hours', 'working hours'], faqMatch: 'What are the customer support hours?', keywords: ['hours', 'business', 'available', 'operating', 'working'] },
  { intent: 'complaint', patterns: ['complaint', 'feedback', 'submit complaint', 'file complaint', 'not satisfied', 'dissatisfied', 'give feedback'], faqMatch: 'How do I submit a complaint or feedback?', keywords: ['complaint', 'feedback', 'dissatisfied'] },
  { intent: 'office_location', patterns: ['office location', 'where is office', 'visit office', 'office address', 'headquarters', 'where are you'], faqMatch: 'Where can I find the T.A Coin office?', keywords: ['office', 'location', 'address', 'visit', 'headquarters'] },
  { intent: 'apply_job', patterns: ['apply job', 'job application', 'career', 'hiring', 'work at', 'employment', 'job opening', 'looking for job'], faqMatch: 'How do I apply for a job at T.A Coin?', keywords: ['job', 'apply', 'career', 'hiring', 'work', 'employment'] },
  { intent: 'work_culture', patterns: ['work culture', 'company culture', 'work environment', 'diversity', 'inclusion'], faqMatch: 'What is the work culture like at T.A Coin?', keywords: ['culture', 'environment', 'diversity', 'inclusion'] },
  { intent: 'job_openings', patterns: ['job openings', 'positions available', 'vacancies', 'current jobs', 'open positions', 'any openings'], faqMatch: 'What positions are currently available at T.A Coin?', keywords: ['positions', 'openings', 'vacancies', 'jobs'] },
  { intent: 'regulated', patterns: ['regulated', 'license', 'legal', 'nbc', 'csx', 'serc', 'compliance', 'is it legal', 'legitimate', 'licensed'], faqMatch: 'Is T.A Coin regulated?', keywords: ['regulated', 'license', 'legal', 'nbc', 'csx', 'serc'] },
  { intent: 'privacy_policy', patterns: ['privacy policy', 'data policy', 'find privacy policy'], faqMatch: 'Where can I find the Privacy Policy?', keywords: ['privacy', 'policy'] },
  { intent: 'terms_conditions', patterns: ['terms and conditions', 'terms of use', 'terms of service', 'tos', 'find terms'], faqMatch: 'Where can I find the Terms and Conditions?', keywords: ['terms', 'conditions', 'service', 'agreement'] },
  { intent: 'qualified_investor', patterns: ['qualified investor', 'investor requirements', 'who can invest', 'eligibility'], faqMatch: 'What is a Qualified Investor?', keywords: ['qualified', 'investor', 'eligibility', 'criteria'] },
  { intent: 'services', patterns: ['what services', 'features', 'what can i do', 'offerings', 'p2p', 'trading', 'platform features'], faqMatch: 'What services does T.A Coin offer?', keywords: ['services', 'features', 'offerings', 'p2p', 'trading'] },
  { intent: 'how_invest', patterns: ['how to invest', 'investment', 'invest money', 'start investing', 'invest in ta coin', 'buy coins'], faqMatch: 'How does investment work on T.A Coin?', keywords: ['invest', 'investment', 'buy', 'purchase'] },
  { intent: 'incentives_dividends', patterns: ['incentives', 'dividends', 'profit sharing', 'returns', 'earnings', 'coin incentives', 'profit'], faqMatch: 'What are Coin incentives and Coin dividends?', keywords: ['incentives', 'dividends', 'profit', 'returns', 'earnings'] },
  { intent: 'projects', patterns: ['what projects', 'airport project', 'techo airport', 'property investment', 'real estate'], faqMatch: 'What projects does T.A Coin invest in?', keywords: ['projects', 'airport', 'techo', 'property'] },
];

export const SYNONYM_MAP = {
  password: ['login', 'credentials', 'passcode'], report: ['complain', 'flag', 'notify', 'alert', 'submit'],
  scam: ['fraud', 'phishing', 'fake', 'suspicious'], money: ['funds', 'cash', 'balance', 'payment'],
  pay: ['payment', 'send', 'transfer', 'transaction'], account: ['profile', 'wallet'],
  delete: ['remove', 'close', 'deactivate', 'cancel', 'terminate'], safe: ['secure', 'security', 'protection'],
  help: ['support', 'assist', 'contact'], job: ['career', 'position', 'work', 'employment', 'hiring'],
  invest: ['investment', 'buy', 'purchase', 'trade'], download: ['install', 'app store', 'google play'],
  verify: ['verification', 'kyc', 'identity'], stuck: ['pending', 'failed', 'error', 'problem'],
  hacked: ['unauthorized', 'compromised', 'stolen'], location: ['address', 'office', 'headquarters'],
  phone: ['call', 'number', 'telephone'], email: ['mail', 'contact'],
};

export const STOP_WORDS = new Set([
  'a','an','the','is','it','in','on','at','to','for','of','and','or','but','not','no','so','if','by','as',
  'be','am','are','was','were','been','has','had','have','do','did','does','will','would','can','could',
  'should','may','might','shall','must','how','what','when','where','who','which','why','whom',
  'i','me','my','we','us','our','you','your','he','she','they','them','this','that','these','those',
  'here','there','with','from','into','about','than','then','just','also','very','some','any','all',
  'each','every','both','few','more','most','other','such','only','own','same','too','out','up','down',
  'please','thanks','thank','hi','hello','hey','okay','ok',
]);
